### ISSUE TITLE
BUG: link to pdf in index.md results in 404

### ISSUE THREAD

**Issue by nvanderperren** [DILCISBoard/CITS-PREMIS#1]
Hi, there's something wrong with the URL of the pdf in `index.md`. I can read the pdf with this url (https://github.com/DILCISBoard/CITS-PREMIS/blob/master/specification/CITS_Preservation_metadata_v1.0.pdf), but I get a 404 with https://citspremis.dilcis.eu/specification/CITS_Archival_Information_v1.0.pdf

**Comment by karinbredenberg** [comment]
Thanks for spotting that! Index.md have been updated with the correct link.
