### ISSUE TITLE
PM63: conflicting obligation and cardinality

### ISSUE THREAD

**Issue by nvanderperren** [DILCISBoard/CITS-PREMIS#2]
PM63 `object/relationship/relatedEventIdentifier` is MUST but cardinality is 0..n. This seems like a bug.

**Comment by prettybits** [comment]
I think you meant PM63 (`object/relationship/relatedEventIdentifier`)? PM62 looks fine to me (MUST, 1..1).

**Comment by nvanderperren** [comment]
woops, indeed.

**Comment by karinbredenberg** [comment]
Thanks for catching that one, yes PM63 should be a "SHOULD" that will be updated in the next version.

**Comment by karinbredenberg** [comment]
Fixed in version 1.0.1
